# Generated by Django 5.2 on 2025-05-16 23:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0002_alter_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_items', to='categories.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_items', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_items', to='stores.store')),
            ],
        ),
    ]
