# Generated by Django 5.2 on 2025-05-18 00:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('store_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='store_items.storeitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
