# Generated by Django 5.2 on 2025-05-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
