# Generated by Django 5.2 on 2025-05-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethodvalue',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
